version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: db_shopping
      POSTGRES_USER: umair
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
